# -*- coding: utf-8 -*-
"""21/4/20 task.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16zWoP1IMXANI4FC01BdjZH8sqtkWr-Ot
"""

import urllib.request
import json

data = {
        "Inputs": {
                "input1":
                [
                    {
                            'symboling': "3",   
                            'normalized-losses': "1",   
                            'make': "alfa-romero",   
                            'fuel-type': "gas",   
                            'aspiration': "std",   
                            'num-of-doors': "two",   
                            'body-style': "convertible",   
                            'drive-wheels': "rwd",   
                            'engine-location': "front",   
                            'wheel-base': "88.6",   
                            'length': "168.8",   
                            'width': "64.1",   
                            'height': "48.8",   
                            'curb-weight': "2548",   
                            'engine-type': "dohc",   
                            'num-of-cylinders': "four",   
                            'engine-size': "130",   
                            'fuel-system': "mpfi",   
                            'bore': "3.47",   
                            'stroke': "2.68",   
                            'compression-ratio': "9",   
                            'horsepower': "111",   
                            'peak-rpm': "5000",   
                            'city-mpg': "21",   
                            'highway-mpg': "27",   
                            'price': "13495",   
                    }
                ],
        },
    "GlobalParameters":  {
    }
}

body = str.encode(json.dumps(data))

url = 'https://ussouthcentral.services.azureml.net/workspaces/180271ab4608462692fcf1f3b117d845/services/9a3ef522e24b41f0a79bded7f1a44739/execute?api-version=2.0&format=swagger'
api_key = 'oqLbTZbZPLhgn4Rff1SoJPAmIQ5+H26B8kucIGw/d9AOSb+OnkN6eEWmtNM46NubooknmI3aio1Do3i81pK1Nw==' # Replace this with the API key for the web service
headers = {'Content-Type':'application/json', 'Authorization':('Bearer '+ api_key)}

req = urllib.request.Request(url, body, headers)

try:
    response = urllib.request.urlopen(req)

    result = response.read()
    print(result)
except urllib.error.HTTPError as error:
    print("The request failed with status code: " + str(error.code))

    # Print the headers - they include the requert ID and the timestamp, which are useful for debugging the failure
    print(error.info())
    print(json.loads(error.read().decode("utf8", 'ignore')))

